name: Docker Windows Installer

on:
  workflow_call:
    inputs:
      version:
        description: 'Application version'
        required: false
        default: '1.0.0'
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: false
        default: '1.0.0'
        type: string

jobs:
  build-docker-installer:
    name: Build Windows Installer with Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build application
      run: |
        ./gradlew build -x test
        ./gradlew createDistributable -x test
        
    - name: Build Docker image for Windows installer
      run: |
        docker build -f Dockerfile.windows-installer -t blackandpink-wine .
        
    - name: Create Windows installer with Docker
      run: |
        docker run --rm -v "$(pwd):/app" blackandpink-wine
        
    - name: Verify installer creation
      run: |
        if [ -f "BlackAndPink-Setup-1.0.0.exe" ]; then
          echo "✅ Windows installer created successfully"
          ls -lh BlackAndPink-Setup-1.0.0.exe
        else
          echo "❌ Windows installer creation failed"
          exit 1
        fi
        
    - name: Upload Windows installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-docker-installer
        path: BlackAndPink-Setup-1.0.0.exe
        retention-days: 30
